/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.planilha.oi.planos;

import java.util.ArrayList;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import projeto.planilha.oi.dao.metodos.PlanoDao;
import projeto.planilha.oi.dao.sql.PlanoDaoJDBC;
import projeto.planilha.oi.model.Plano;
import projeto.planilha.oi.venda.LancaVendas;

/**
 *
 * @author ericvdias
 */
public class ConsultaPlanos extends javax.swing.JPanel {
 PlanoDao planoDao = new PlanoDaoJDBC();
    /**
     * Creates new form CadastroDePlanos
     */
    public ConsultaPlanos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDinamico = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbListaPlanos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnEditarPlano = new javax.swing.JButton();
        btnExcluirPlano = new javax.swing.JButton();
        btnAdicionarPlano = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtCampoBusca = new javax.swing.JTextField();
        btnBuscarPlano = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelDinamico.setLayout(new java.awt.BorderLayout());

        tbListaPlanos.setBackground(new java.awt.Color(204, 204, 204));
        tbListaPlanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Tipo", "Categoria"
            }
        ));
        jScrollPane2.setViewportView(tbListaPlanos);

        panelDinamico.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnEditarPlano.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-lápis2-32.png"))); // NOI18N
        btnEditarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPlanoActionPerformed(evt);
            }
        });

        btnExcluirPlano.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/icons8-apagar-para-sempre-48.png"))); // NOI18N
        btnExcluirPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirPlanoActionPerformed(evt);
            }
        });

        btnAdicionarPlano.setBackground(new java.awt.Color(255, 255, 255));
        btnAdicionarPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/selecionado-32_2.png"))); // NOI18N
        btnAdicionarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPlanoActionPerformed(evt);
            }
        });

        btnFechar.setBackground(new java.awt.Color(255, 255, 255));
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/sair32.png"))); // NOI18N
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAdicionarPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnEditarPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnExcluirPlano, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btnAdicionarPlano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarPlano)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        panelDinamico.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(786, 80));

        btnBuscarPlano.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/busca2.png"))); // NOI18N
        btnBuscarPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPlanoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtCampoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCampoBusca))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panelDinamico.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        add(panelDinamico, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPlanoActionPerformed
        if (tbListaPlanos.getSelectedRow() >= 0) {
            //==> Pega o cógido do cliente selecionado na tabela <==\\
            String tipo = "update";
            int linha = tbListaPlanos.getSelectedRow();

            int codigo = (int) tbListaPlanos.getModel().getValueAt(linha, 0);
            //JPanel onde tem a tabela

            //==> Abre a tela de edição, passando o código do cliente <==\\
            CadastraPlanos adicionarPlanos = new CadastraPlanos(codigo, tipo);
            panelDinamico.removeAll();
            panelDinamico.add(adicionarPlanos);
            panelDinamico.validate();
            panelDinamico.repaint();
        } else {
            //JOptionPane.showMessageDialog(null, "Selecione um Planos!");
        }
    }//GEN-LAST:event_btnEditarPlanoActionPerformed

    private void btnExcluirPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirPlanoActionPerformed
        /*
        if (tbListaPlanos.getSelectedRow() >= 0) {

            //int resposta = JOptionPane.showConfirmDialog(null, "Confirma a exclusão do cliente?", "Excluir Planos!", JOptionPane.YES_NO_OPTION);
            //if (resposta == 0) {
                int linha = tbListaPlanos.getSelectedRow();
                int codigo = (int) tbListaPlanos.getModel().getValueAt(linha, 0);

                //==> Chama o método para excluir o cliente selecionado <==\\
                planoDao.excluirPlano(codigo);

                //==> Faz nova busca, após a exclusão, atualizando a tabela de clientes <==\\
                ((DefaultTableModel) tbListaPlanos.getModel()).setRowCount(0);
                planoDao.buscarPlanos();
                DefaultTableModel modeloDeColuna = (DefaultTableModel) tbListaPlanos.getModel();
                ArrayList<Plano> listaDePlanoss = planoDao.buscarPlanos();

                for (int i = 0; i < listaDePlanoss.size(); i++) {
                    Plano exibePlanos = listaDePlanoss.get(i);
                    String nome = txtCampoBusca.getText();

                    //==> Faz a busca do cliente por qualquer parte do seu nome <==\\
                    if (exibePlanos.getNome().contains(nome)) {

                        Object[] linha1 = new Object[5];

                        linha1[0] = exibePlanos.getCodigo();
                        linha1[1] = exibePlanos.getNome();
                        linha1[2] = exibePlanos.getTelefone();
                        linha1[3] = exibePlanos.getCpfCnpj();
                        linha1[4] = exibePlanos.getEmail(); // Endereco Criar classe.
                        modeloDeColuna.addRow(linha1);
                    }
                }
                //JOptionPane.showMessageDialog(null, "Planos Removido!");
                //}
        } else {
            //JOptionPane.showMessageDialog(null, "Selecione um Planos!");
        }
        */
    }//GEN-LAST:event_btnExcluirPlanoActionPerformed

    private void btnAdicionarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPlanoActionPerformed

        String tipo = "insert";

        //==> Faz  uma busca dos clientes para trazer o último código cadastrado <==\\
        int codigoNovoPlanos = 0;
        /*
        
        */
        //==> Abre a tela para inserir dados do cliente, passando o código e o tipo (insert=novo ou update=atualiza) <==\\
        CadastraPlanos adicionarPlanos = new CadastraPlanos(codigoNovoPlanos, tipo);
        panelDinamico.removeAll();
        panelDinamico.add(adicionarPlanos);
        panelDinamico.validate();
        panelDinamico.repaint();
    }//GEN-LAST:event_btnAdicionarPlanoActionPerformed

    private void btnBuscarPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPlanoActionPerformed
        ((DefaultTableModel) tbListaPlanos.getModel()).setRowCount(0);

        planoDao.buscarPlanos();

        DefaultTableModel modeloDeColuna = (DefaultTableModel) tbListaPlanos.getModel();
        ArrayList<Plano> listaDePlanos = planoDao.buscarPlanos();

        for (int i = 0; i < listaDePlanos.size(); i++) {
            Plano exibePlanos = listaDePlanos.get(i);
            String nome = txtCampoBusca.getText().toUpperCase();

            //==> Faz a busca do cliente por qualquer parte do seu nome <==\\
            if (exibePlanos.getNome().contains(nome)) {

                Object[] linha = new Object[5];

                linha[0] = exibePlanos.getCodigo();
                linha[1] = exibePlanos.getNome();
                linha[2] = exibePlanos.getTipo();
                linha[3] = exibePlanos.getCategoria();
                
                modeloDeColuna.addRow(linha);
            }
        }
    }//GEN-LAST:event_btnBuscarPlanoActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        
        /*
        LancaVendas consultaVendas = new LancaVendas();
        panelDinamico.removeAll();
        panelDinamico.add(consultaVendas);
        panelDinamico.validate();
        panelDinamico.repaint();
        */
        
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPlano;
    private javax.swing.JButton btnBuscarPlano;
    private javax.swing.JButton btnEditarPlano;
    private javax.swing.JButton btnExcluirPlano;
    private javax.swing.JButton btnFechar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelDinamico;
    private javax.swing.JTable tbListaPlanos;
    private javax.swing.JTextField txtCampoBusca;
    // End of variables declaration//GEN-END:variables
}
